version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: eecshelp
      MYSQL_DATABASE: eecshelp
  web:
    build: .
    env_file:
      - dev.env
    volumes:
      - .:/usr/src/eecshelp
    ports:
      - "9292:9292"
    depends_on:
      - db
